[build]
  publish = "build"
  command = "npm run build"

# Do NOT store secret keys in this file. Set environment variables in Netlify UI:
# Site settings -> Build & deploy -> Environment -> New variable
# e.g. REACT_APP_GEMINI_API_KEY

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200